UPDATE student SET time_exited = Now() WHERE matric_number = 'A8250131U' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1947203H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7419872D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4997492F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6293691B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2534791Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7883390Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5902475K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0982458I' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5605411S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2296688M' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6415864S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8935359E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0847941B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4116721W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9331996R' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7264303K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7155931B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1083692D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3841373Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6135993O' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2217873Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4311200G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5323822J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6733429P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3154007E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9558798G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2856556V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7601638C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8802123Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6873910Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8971521U' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5555220H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4642328O' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0283505P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4850849K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6901227U' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5511785L' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9070434F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9276652K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0948640E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5034626R' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7662933E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7045429D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9757068K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8219593H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8827362F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6805468D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7196074M' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6026381B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5404719F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4408251E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4850237H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1354493D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1296296Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3528769I' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1849051X' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5666497X' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7823932Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8236520Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7615822C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6634391A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5096170G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0411403Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1985503Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0623981C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7738900A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0963029P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2589248S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5052409U' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3932698H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4148018K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4099012B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7619992M' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0819931Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7622913G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4717816Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5769271K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5410698Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2811420Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2718736K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4121559S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9443339W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4625625D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3238171N' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7203869B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6223607W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8293233J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5170593C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2841605E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0720649Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3693790R' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8254419L' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1648895D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0904395K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3575077S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0172747L' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7340613S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5803329H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3632494P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8250131U' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1947203H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7419872D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4997492F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6293691B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2534791Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7883390Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5902475K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0982458I' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5605411S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2296688M' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6415864S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8935359E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0847941B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4116721W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9331996R' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7264303K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7155931B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1083692D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3841373Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6135993O' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2217873Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4311200G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5323822J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6733429P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3154007E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9558798G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2856556V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7601638C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8802123Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6873910Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8971521U' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5555220H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4642328O' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0283505P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4850849K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6901227U' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5511785L' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9070434F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9276652K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0948640E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5034626R' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7662933E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7045429D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9757068K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8219593H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8827362F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6805468D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7196074M' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6026381B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5404719F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4408251E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4850237H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1354493D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1296296Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3528769I' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1849051X' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5666497X' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7823932Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8236520Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7615822C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6634391A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5096170G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0411403Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1985503Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0623981C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7738900A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0963029P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2589248S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5052409U' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3932698H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4148018K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4099012B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7619992M' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0819931Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7622913G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4717816Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5769271K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5410698Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2811420Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2718736K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4121559S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9443339W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4625625D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3238171N' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7203869B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6223607W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8293233J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5170593C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2841605E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0720649Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3693790R' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8254419L' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1648895D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0904395K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3575077S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0172747L' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7340613S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5803329H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3632494P' ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
