UPDATE student SET time_exited = Now() WHERE matric_number = 'A0453953N' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1345486X' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1025008R' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0104635D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5802547V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3795094U' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5995755S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7889501J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6470775G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6194653Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3421550R' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7631487E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8113812G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5920953D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3357598D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7772157B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6054000W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1952132J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2313350C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0391994N' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0852392Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6348374V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6539040P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8885684X' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6620285A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8052032F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7741448P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4941732W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6816272O' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9679732A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0854731S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0037044A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3971677I' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2179849J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7053522Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5825028I' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4418705Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3860140X' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7211340O' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4566241H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3686058U' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5775506Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9003867Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4812841E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4070343W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8817980S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8555590P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0911612L' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1524440K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1717490I' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3228505H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9689918Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9946941K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9810551S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8518588Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2452778F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3416966P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2570159R' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4042126W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8781648Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3960646E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0117554F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9792529M' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1666570J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2317558P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5518449X' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5383367B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9225225D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9705851Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9185149Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2421951O' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6036221Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4372923Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8414838Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1662624H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0671415A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8263186Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2935776V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5819604Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0770612A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8151170G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7682955A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3457668H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0631635N' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4872883P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6713847A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1907072P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4291975L' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6951622N' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4415599S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0451383H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5010372Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9840211H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4046556R' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1176089K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4620417O' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2516407H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1366954N' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0866594Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4247954J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6562498Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7526770Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7740247Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7924516Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5418554D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8034494L' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4763204U' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1004489S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6276746L' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9292436Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7730361X' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5776093D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6998936W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5486374N' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7647750Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4092262H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1066842R' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2814171P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4195009Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5494626H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7833568H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7994336W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1715754P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9942670Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4316574C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3803657Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9167318H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9409960T' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7888095H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0808023J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2930138V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3300515Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2489969B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5462634C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7329320C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8398413V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2145392D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6503241J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4476221E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5234165L' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6324454I' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5793259O' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1455008F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7044550C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6190262B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5600534D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1289121S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0689136D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0690194H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2163222N' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2545676Y' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6634259H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5497041G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6202145B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7677038Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7043360J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5329125F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4088397B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2574287H' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0048794T' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0591625P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1919489X' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7041830L' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5499543W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1741037N' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7905255D' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9013417Z' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7455013E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0333858K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4695663Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0158727W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0763224T' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1691934E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4118129A' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1416467G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4557325E' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1667891U' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0833498W' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6472955F' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4833788M' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7715249B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7430558V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0524902G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8913043G' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6250300P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9809806B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A6331270C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A9846903P' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0391639J' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4280192S' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5156192Q' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A0263603V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A4985243V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A1578025O' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8048302B' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A5400587K' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A8626050C' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A3853422O' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A2237367V' ;
UPDATE student SET time_exited = Now() WHERE matric_number = 'A7828849E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0453953N' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1345486X' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1025008R' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0104635D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5802547V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3795094U' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5995755S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7889501J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6470775G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6194653Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3421550R' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7631487E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8113812G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5920953D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3357598D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7772157B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6054000W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1952132J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2313350C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0391994N' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0852392Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6348374V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6539040P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8885684X' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6620285A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8052032F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7741448P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4941732W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6816272O' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9679732A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0854731S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0037044A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3971677I' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2179849J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7053522Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5825028I' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4418705Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3860140X' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7211340O' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4566241H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3686058U' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5775506Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9003867Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4812841E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4070343W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8817980S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8555590P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0911612L' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1524440K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1717490I' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3228505H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9689918Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9946941K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9810551S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8518588Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2452778F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3416966P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2570159R' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4042126W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8781648Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3960646E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0117554F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9792529M' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1666570J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2317558P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5518449X' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5383367B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9225225D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9705851Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9185149Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2421951O' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6036221Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4372923Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8414838Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1662624H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0671415A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8263186Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2935776V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5819604Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0770612A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8151170G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7682955A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3457668H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0631635N' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4872883P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6713847A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1907072P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4291975L' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6951622N' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4415599S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0451383H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5010372Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9840211H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4046556R' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1176089K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4620417O' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2516407H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1366954N' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0866594Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4247954J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6562498Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7526770Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7740247Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7924516Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5418554D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8034494L' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4763204U' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1004489S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6276746L' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9292436Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7730361X' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5776093D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6998936W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5486374N' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7647750Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4092262H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1066842R' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2814171P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4195009Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5494626H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7833568H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7994336W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1715754P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9942670Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4316574C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3803657Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9167318H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9409960T' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7888095H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0808023J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2930138V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3300515Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2489969B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5462634C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7329320C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8398413V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2145392D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6503241J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4476221E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5234165L' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6324454I' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5793259O' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1455008F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7044550C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6190262B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5600534D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1289121S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0689136D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0690194H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2163222N' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2545676Y' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6634259H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5497041G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6202145B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7677038Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7043360J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5329125F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4088397B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2574287H' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0048794T' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0591625P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1919489X' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7041830L' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5499543W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1741037N' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7905255D' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9013417Z' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7455013E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0333858K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4695663Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0158727W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0763224T' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1691934E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4118129A' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1416467G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4557325E' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1667891U' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0833498W' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6472955F' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4833788M' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7715249B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7430558V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0524902G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8913043G' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6250300P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9809806B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A6331270C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A9846903P' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0391639J' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4280192S' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5156192Q' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A0263603V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A4985243V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A1578025O' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8048302B' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A5400587K' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A8626050C' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A3853422O' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A2237367V' ;
UPDATE library_system SET time_exited = Now() WHERE matric_number = 'A7828849E' ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'YNLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'YNLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'YNLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'YNLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'YNLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'YNLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'YNLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'YNLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  1 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  3 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MULB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'SLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CHLB' AND level =  6 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  4 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CLB' AND level =  5 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'CJKLLB' AND level =  2 ;
UPDATE available SET available_seats = available_seats + 1 WHERE library =  'MLB' AND level =  5 ;
