INSERT INTO department VALUES ('Science', 'Mathematics' );
INSERT INTO department VALUES ('Science', 'Information Science' );
INSERT INTO department VALUES ('Science', 'Physics' );
INSERT INTO department VALUES ('Science', 'Astronomy' );
INSERT INTO department VALUES ('Science', 'Earth and Planetary Physics' );
INSERT INTO department VALUES ('Science', 'Earth and Planetary Environmental Science' );
INSERT INTO department VALUES ('Science', 'Chemistry' );
INSERT INTO department VALUES ('Science', 'Biophysics and Biochemistry' );
INSERT INTO department VALUES ('Science', 'Biological Science' );
INSERT INTO department VALUES ('Science', 'Bioinformatics' );
INSERT INTO department VALUES ('Science', 'System Biology' );
INSERT INTO department VALUES ('Business', 'Business Administration' );
INSERT INTO department VALUES ('Business', 'Accounting' );
INSERT INTO department VALUES ('Design & Engineering', 'Architecture' );
INSERT INTO department VALUES ('Design & Engineering', 'Biomedical Engineering' );
INSERT INTO department VALUES ('Design & Engineering', 'Chemical Engineering' );
INSERT INTO department VALUES ('Design & Engineering', 'Civil Engineering' );
INSERT INTO department VALUES ('Design & Engineering', 'Computer Engineering' );
INSERT INTO department VALUES ('Design & Engineering', 'Electrical Engineering' );
INSERT INTO department VALUES ('Design & Engineering', 'Engineering Science' );
INSERT INTO department VALUES ('Design & Engineering', 'Environmental Engineering' );
INSERT INTO department VALUES ('Design & Engineering', 'Industrial Design' );
INSERT INTO department VALUES ('Design & Engineering', 'Industrial & Systems Engineering' );
INSERT INTO department VALUES ('Design & Engineering', 'Infrastructure & Project Management' );
INSERT INTO department VALUES ('Design & Engineering', 'Landscape Architecture' );
INSERT INTO department VALUES ('Design & Engineering', 'Materials Science & Engineering' );
INSERT INTO department VALUES ('Design & Engineering', 'Mechanical Engineering' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Chinese Studies' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Japanese Studies' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Malay Studies' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Southeast Asian Studies' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Asian Studies Programme' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'English Language & Literature' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'History' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Philosophy' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Communications and New Media' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Economics' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Geography' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Political Science' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Psychology' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Social Work' );
INSERT INTO department VALUES ('Arts & Social Sciences', 'Sociology' );
INSERT INTO department VALUES ('Medicine', 'Medicine');
INSERT INTO department VALUES ('Medicine', 'Microbiology & Immunology');
INSERT INTO department VALUES ('Medicine', 'Orthopaedic Surgery');
INSERT INTO department VALUES ('Medicine', 'Pathology');
INSERT INTO department VALUES ('Medicine', 'Physiology');
INSERT INTO department VALUES ('Medicine', 'Pharmacology');
INSERT INTO department VALUES ('Dentistry', 'Dentistry');
INSERT INTO department VALUES ('Computing', 'Computer Science');
INSERT INTO department VALUES ('Computing', 'Information Systems and Analytics');
INSERT INTO department VALUES ('Law', 'Law');
